<a href="https://colab.research.google.com/github/optimistme88/pytorch_tutorial/blob/main/tensor_ops.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import torch

my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [2]:
# reshape and view

my_torch = my_torch.reshape(2, 5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [3]:
my_torch2 = my_torch.view(2, 5)
my_torch2

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [5]:
my_torch3 = my_torch[:, 1]
my_torch3

tensor([1, 6])

In [9]:
my_torch4 = torch.arange(10)
my_torch4
my_torch4[1:5]
my_torch4[5] = 9876
my_torch4

tensor([   0,    1,    2,    3,    4, 9876,    6,    7,    8,    9])

In [4]:
tensor_a = torch.tensor([1, 2, 3, 4])
tensor_b = torch.tensor([5, 6, 7, 8])

# Addition
tensor_a + tensor_b

# Addition Longhand
torch.add(tensor_a, tensor_b)

# subtraction
tensor_b - tensor_a

# subtraction fn
torch.sub(tensor_b, tensor_a)

# mul
tensor_b * tensor_a

# Multiplication longhand
torch.mul(tensor_a, tensor_b)


tensor([ 5, 12, 21, 32])

In [17]:
# Division

tensor_b / tensor_a

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [18]:
# Division Longhand
torch.div(tensor_b, tensor_a)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [19]:
# Remainder modulus

tensor_b % tensor_a

tensor([0, 0, 1, 0])

In [20]:
# remainder longhand

torch.remainder(tensor_b, tensor_a)

tensor([0, 0, 1, 0])

In [21]:
# exponent

torch.pow(tensor_b, tensor_a)

tensor([   5,   36,  343, 4096])

In [12]:
tensor_a.add(tensor_b)

tensor_a

# add and re-assignment
tensor_a.add_(tensor_b)

tensor_a

tensor_b

tensor_a

tensor([26, 32, 38, 44])