<a href="https://colab.research.google.com/github/optimistme88/pytorch_tutorial/blob/main/tensor_ops.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [2]:
# reshape and view

my_torch = my_torch.reshape(2, 5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [3]:
my_torch2 = my_torch.view(2, 5)
my_torch2

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [5]:
my_torch3 = my_torch[:, 1]
my_torch3

tensor([1, 6])

In [9]:
my_torch4 = torch.arange(10)
my_torch4
my_torch4[1:5]
my_torch4[5] = 9876
my_torch4

tensor([   0,    1,    2,    3,    4, 9876,    6,    7,    8,    9])